name: Build on merge into main
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install

            - name: Test
              run: yarn test

            - name: Build
              run: yarn build
